REPO_ID="baffo32/decapoda-research-llama-7B-hf"
use_gpu=False
your_image_data="/path/to/dataset/"
reference_summary='example summarised text'
API_URL="http://127.0.0.1:8000/summarize/"
device_map=   {
    "model.embed_tokens": 0,
    "model.layers.0": 0,
    "model.layers.1": 0,
    "model.layers.2": 0,
    "model.layers.3": 0,
    "model.layers.4": 0,
    "model.layers.5.self_attn": 0,
    "model.layers.5.input_layernorm": "cpu",
    "model.layers.5.post_attention_layernorm": "cpu",
    "model.layers.6": "cpu",
    "model.layers.7": "cpu",
    "model.layers.8": "cpu",
    "model.layers.9": "cpu",
    "model.layers.10": "cpu",
    "model.layers.11": "cpu",
    "model.layers.12.self_attn": "cpu",
    "model.layers.12.mlp.gate_proj": "cpu",
    "model.layers.12.mlp.up_proj": "disk",
    "model.layers.12.mlp.down_proj": "disk",
    "model.layers.12.mlp.act_fn": "disk",
    "model.layers.12.input_layernorm": "disk",
    "model.layers.12.post_attention_layernorm": "disk",
    "model.layers.13": "disk",
    "model.layers.14": "disk",
    "model.layers.15": "disk",
    "model.layers.16": "disk",
    "model.layers.17": "disk",
    "model.layers.18": "disk",
    "model.layers.19": "disk",
    "model.layers.20": "disk",
    "model.layers.21": "disk",
    "model.layers.22": "disk",
    "model.layers.23": "disk",
    "model.layers.24": "disk",
    "model.layers.25": "disk",
    "model.layers.26": "disk",
    "model.layers.27": "disk",
    "model.layers.28": "disk",
    "model.layers.29": "disk",
    "model.layers.30": "disk",
    "model.layers.31": "disk",
    "model.norm": "disk",
    "model.rotary_emb": "disk",
    "lm_head": "disk",
    "model.layers.5.mlp": "cpu"
}